name: 🚀 Deploy
run-name: Running Deploy for ${{ github.ref }} on ${{ github.event_name }} event 🚀
on:
  push:
    branches:
      - main
jobs:
  push-to-registry:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: aran159/simple-service:latest

  deploy:
    needs: push-to-registry
    runs-on: ubuntu-latest
    steps:
      - name: Deploy latest image tag in Render
        run: curl "${{ secrets.DEPLOY_WEBHOOK_URL }}&imgURL=docker.io%2Faran159%2Fsimple-service%3Alatest"
